/-
Copyright (c) 2020 Anne Baanen. All rights reserved.
SPDX-License-Identifier: Apache-2.0
Authors: Johannes Hölzl, Mario Carneiro, Alexander Bentkamp, Anne Baanen

The finite exchange induction is adapted from Mathlib's
Mathlib/LinearAlgebra/LinearIndependent/Lemmas.lean.
https://www.apache.org/licenses/LICENSE-2.0
-/

import Textbooks.LinearAlgebra.Chapter01.Bases

namespace LinearAlgebra.Chapter01

open Submodule Set

variable {K V : Type*} [Field K] [AddCommGroup V] [Module K V]

/-- Lemma: an independent vector cannot be generated by other
members of the independent set. Compare the coefficient tuple with a unit tuple. -/
theorem independent_not_mem_span {s t : Set V} (hs : LinearIndepOn K id s)
    (ht : t ⊆ s) {x : V} (hx : x ∈ s) (hxt : x ∉ t) : x ∉ span K t := by
  classical

  intro hm

  have hm' : x ∈ span K (id '' t) := by
    simpa only [image_id] using hm

  obtain ⟨a, ha, he⟩ := (Finsupp.mem_span_image_iff_linearCombination K).mp hm'

  have has : a ∈ Finsupp.supported K K s := by
    exact (Finsupp.mem_supported K a).mpr (ht.trans' ((Finsupp.mem_supported K a).mp ha))

  have eq := linearIndepOn_iffₛ.mp hs a has (Finsupp.single x 1)
    (Finsupp.single_mem_supported K 1 hx) (by simpa using he)

  have haz : a x = 0 := (Finsupp.mem_supported' K a).mp ha x hxt

  have := congrArg (fun f : V →₀ K => f x) eq

  simp only [haz, Finsupp.single_eq_same, zero_ne_one] at this

/-- Lemma: an independent subset cannot span a missing member. -/
theorem independent_span_subset_eq {s t : Set V} (hs : LinearIndepOn K id s)
    (ht : t ⊆ s) (hst : s ⊆ span K t) : s = t := by
  apply Subset.antisymm _ ht
  intro x hx
  by_contra hn
  exact independent_not_mem_span hs ht hx hn (hst hx)

/-- Lemma: solve for a generator with nonzero coefficient. -/
theorem span_insert_exchange {s : Set V} {x y : V}
    (hx : x ∈ span K (insert y s)) (hn : x ∉ span K s) :
    y ∈ span K (insert x s) := by
  obtain ⟨a, z, hz, he⟩ := mem_span_insert.mp hx

  have ha : a ≠ 0 := by
    intro h
    apply hn
    rw [h, zero_smul, zero_add] at he
    rw [he]
    exact hz

  apply mem_span_insert.mpr
  refine ⟨a⁻¹, -(a⁻¹ • z), (span K s).neg_mem ((span K s).smul_mem _ hz), ?_⟩
  rw [he, smul_add, smul_smul, inv_mul_cancel₀ ha, one_smul, add_neg_cancel_right]

/-- Theorem: replace finite generators by independent vectors
without increasing the number of generators. -/
theorem finite_exchange {s : Set V} {t : Finset V} (hs : LinearIndepOn K id s)
    (hst : s ⊆ span K (t : Set V)) :
    ∃ u : Finset V, (u : Set V) ⊆ s ∪ (t : Set V) ∧ s ⊆ u ∧ u.card = t.card := by
  classical

  have step : ∀ t : Finset V, ∀ s' : Finset V,
      (s' : Set V) ⊆ s → s ∩ (t : Set V) = ∅ →
      s ⊆ span K (↑(s' ∪ t) : Set V) →
      ∃ u : Finset V, (u : Set V) ⊆ s ∪ (t : Set V) ∧
        s ⊆ u ∧ u.card = (s' ∪ t).card := by
    intro t
    induction t using Finset.induction_on with
    | empty =>
      intro s' hs' _ hsp

      have he : s = (s' : Set V) := independent_span_subset_eq hs hs' (by simpa using hsp)

      exact ⟨s', by simp [he]⟩

    | @insert y t hyt ih =>
      intro s' hs' hdis hsp

      have hys : y ∉ s := fun hy => by
        have : y ∈ s ∩ (↑(insert y t) : Set V) := ⟨hy, Finset.mem_insert_self _ _⟩

        rwa [hdis] at this

      have hys' : y ∉ s' := fun hy => hys (hs' hy)

      have hdis' : s ∩ (t : Set V) = ∅ := by
        apply eq_empty_of_subset_empty
        exact (inter_subset_inter_right s (by simp : (t : Set V) ⊆ ↑(insert y t))).trans
          (le_of_eq hdis)

      by_cases hold : s ⊆ span K (↑(s' ∪ t) : Set V)

      · obtain ⟨u, hu, hsu, hcard⟩ := ih s' hs' hdis' hold

        have hyu : y ∉ u := fun hy => (hu hy).elim hys hyt

        refine ⟨insert y u, ?_, hsu.trans (by simp), ?_⟩

        · intro z hz
          rcases Finset.mem_insert.mp hz with rfl | hz

          · exact Or.inr (Finset.mem_insert_self _ _)
          · exact (hu hz).imp_right (fun hz => Finset.mem_insert_of_mem hz)
        · simp [hcard, hyt, hys', hyu]

      · obtain ⟨x, hxs, hxn⟩ := not_subset.mp hold

        have hxnew : x ∉ s' ∪ t := fun hx => hxn (subset_span hx)

        have hsp' : s ⊆ span K (↑(insert x s' ∪ t) : Set V) := by
          intro z hz

          have hinc : (↑(s' ∪ insert y t) : Set V) ⊆ insert y (insert x ↑(s' ∪ t)) := by
            simp only [Finset.coe_union, Finset.coe_insert]
            intro a ha
            rcases ha with ha | ha

            · exact Or.inr (Or.inr (Or.inl ha))
            · rcases ha with rfl | ha
              · exact Or.inl rfl
              · exact Or.inr (Or.inr (Or.inr ha))

          have hzm := span_mono hinc (hsp hz)

          have hxm : x ∈ span K (insert y (↑(s' ∪ t) : Set V)) := by
            simpa [Finset.union_insert, Finset.coe_insert] using hsp hxs

          have hym := span_insert_exchange hxm hxn

          rw [span_insert_eq_span hym] at hzm
          simpa only [Finset.insert_union, Finset.coe_insert, SetLike.mem_coe] using hzm

        obtain ⟨u, hu, hsu, hcard⟩ := ih (insert x s') (by simp [insert_subset_iff, hxs, hs'])
          hdis' hsp'

        refine ⟨u, hu.trans (union_subset_union_right s (by simp)), hsu, ?_⟩
        simp [hcard, hxnew, hyt, hys']

  have he : (t.filter fun x => x ∈ s) ∪ (t.filter fun x => x ∉ s) = t := by
    ext x
    by_cases x ∈ s <;> simp [*]

  obtain ⟨u, hu, hsu, hcard⟩ := step (t.filter fun x => x ∉ s)
    (t.filter fun x => x ∈ s) (by simp [Set.subset_def])
    (by simp +contextual [Set.ext_iff]) (by rwa [he])

  exact ⟨u, hu.trans (union_subset_union_right s (Finset.filter_subset _ _)),
    hsu, by simpa [he] using hcard⟩

/-- Theorem: an independent finite set is no larger than a
finite spanning set. This is the finite-dimensional exchange inequality. -/
theorem independent_card_le {s t : Finset V} (hs : LinearIndepOn K id (s : Set V))
    (hst : (s : Set V) ⊆ span K (t : Set V)) : s.card ≤ t.card := by
  obtain ⟨u, _, hsu, hcard⟩ := finite_exchange hs hst

  rw [← hcard]
  exact Finset.card_le_card hsu

end LinearAlgebra.Chapter01
