#!/usr/bin/env python3
"""Generate deterministic Jekyll book data from the canonical manifest."""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

import yaml

from book_manifest import load_manifest

REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT = REPO_ROOT / "site" / "_data" / "books.yml"
NARRATIVE_DIR = REPO_ROOT / "site" / "books"
SITE_FIELDS = ("slug", "title", "short_title", "status", "order", "site")
STATUS_LABELS = {
    "draft": "Draft",
    "review": "In Review",
    "published": "Published",
    "archived": "Archived",
}
SLUG_FIELD = re.compile(r"(?m)^slug:\s*([a-z0-9]+(?:-[a-z0-9]+)*)\s*$")


def site_books(manifest: dict) -> list[dict]:
    books = []
    for source in manifest["books"]:
        if not source["site"]:
            continue
        book = {field: source.get(field) for field in SITE_FIELDS}
        book["display_short_title"] = source.get("short_title") or source["title"]
        book["status_label"] = STATUS_LABELS[source["status"]]
        books.append(book)
    return books


def narrative_sources(directory: Path = NARRATIVE_DIR) -> dict[str, Path]:
    sources: dict[str, Path] = {}
    for path in sorted(directory.glob("*.md")):
        text = path.read_text(encoding="utf-8")
        matches = SLUG_FIELD.findall(text)
        if len(matches) != 1:
            raise ValueError(f"{path} must declare exactly one front-matter slug")
        slug = matches[0]
        if slug in sources:
            raise ValueError(f"duplicate site narrative slug: {slug}")
        if path.stem != slug:
            raise ValueError(f"site narrative filename {path.name} does not match slug {slug}")
        sources[slug] = path
    return sources


def validate_narratives(books: list[dict], directory: Path = NARRATIVE_DIR) -> None:
    expected = {book["slug"] for book in books}
    actual = set(narrative_sources(directory))
    missing = sorted(expected - actual)
    extra = sorted(actual - expected)
    if missing:
        raise ValueError("missing site narrative source(s): " + ", ".join(missing))
    if extra:
        raise ValueError("unregistered or site-disabled narrative source(s): " + ", ".join(extra))


def render_site_data(manifest: dict, narrative_dir: Path = NARRATIVE_DIR) -> str:
    books = site_books(manifest)
    validate_narratives(books, narrative_dir)
    return "# Generated by scripts/generate-site-data.py; do not edit.\n" + yaml.safe_dump(
        books, allow_unicode=True, sort_keys=False,
    )


def generate(*, check: bool = False, output: Path = OUTPUT) -> int:
    expected = render_site_data(load_manifest())
    if check:
        if not output.is_file() or output.read_text(encoding="utf-8") != expected:
            display = output.relative_to(REPO_ROOT) if output.is_relative_to(REPO_ROOT) else output
            print(f"error: generated site data is stale: {display}", file=sys.stderr)
            return 1
        print("Generated site data is up to date.")
        return 0
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(expected, encoding="utf-8")
    display = output.relative_to(REPO_ROOT) if output.is_relative_to(REPO_ROOT) else output
    print(f"Generated {display}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail instead of updating stale output")
    args = parser.parse_args()
    try:
        return generate(check=args.check)
    except ValueError as error:
        print(f"error: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
